name: Deploy Webserver Nginx to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Deploy Nginx configuration
        run: |
          scp -o StrictHostKeyChecking=no -r nginx-config/* ec2-user@43.205.117.221:/etc/nginx/
          ssh -o StrictHostKeyChecking=no ec2-user@43.205.117.221 'sudo nginx -t && sudo systemctl reload nginx'

